# Generated by Django 5.2.17 on 2026-09-22 08:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('hold', 'hold')], max_length=8)),
                ('priority', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effort', models.DurationField(null=True)),
                ('created', models.DateTimeField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=list, size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('meta', models.JSONField(default=dict)),
                ('active', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('review', django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True)),
                ('weight', django.contrib.postgres.fields.ranges.IntegerRangeField(null=True)),
                ('peer', models.GenericIPAddressField(null=True)),
                ('payload', models.BinaryField(null=True)),
                ('document', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='shop.team')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watching', to='shop.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['labels'], name='shop_ticket_labels_6f8593_gin'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['meta'], name='shop_ticket_meta_a9e88c_gin'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['document'], name='shop_ticket_documen_34b288_gin'),
        ),
    ]
